apiVersion: v1
kind: Secret
metadata:
  name: my-secret
data:
  .env: REFUQUJBU0VfVVJMOiBEQVRBQkFTRV9VUkw9XCJwb3N0Z3Jlc3FsOi8vYWRtaW46cGFzc3dvcmRAbG9jYWxob3N0OjU0MzJcIiwKICBDQUNIRV9TSVpFOiAxMDAwLAogIFBBWU1FTlRfR0FURVdBWV9VUkw6IGh0dHBzOi8vcGF5bWVudC1nYXRld2F5LmV4YW1wbGUuY29tLAogIE1BWF9DQVJUX0lURU1TOiA1MCwKICBTRVNTSU9OX1RJTUVPVVQ6IDM2MDA=